[DEADEYE.DEBUG]
framerate = 200
boiler = 50
gear = 0

[BOILER]
gui = true

[BOILER.CAMERA]
width  = 1280
height = 1024

#exposure = 1.0 # kentwood afternoon
#exposure = -2.2 # states 4/28
#exposure = -2.2
exposure = -1.0

[BOILER.FRAME]
hsv_lower = [80, 100, 100]
hsv_upper = [100, 255, 255]
#min_arc_length = 250.0
min_arc_length = 200.0
aspect_ratio_min = 2.0
aspect_ratio_max = 5.0
discontinuity_threshold = 50


[GEAR.CAMERA]

[GEAR.FRAME]
hsv_lower = [70, 100, 100]
hsv_upper = [90, 255, 255]
min_arc_length = 50.0
azimuth_offset = 320

[LINK]
port = 5800
address = "10.27.67.2"
mode = "boiler"
