[STEAMWORKS]

grapher = false

[STEAMWORKS.CLIMBER]
capture_voltage =  4.0
climb_voltage   =  12.0
finish_voltage  =  4.0
capture_current =  4.0
finish_current  = 10.0
climb_distance  =  26000

    [[STEAMWORKS.CLIMBER.TALON]]
    name = "master"
    type = "voltage"
    feedback_device = 0 # quad
    neutral_mode    = 1 # brake
    limit_mode      = 2 # disabled
    encoder_reversed = false
    output_reversed  = true
    current_limit    = 30 # amps, 0 disables

    voltage_ramp_rate = 0.0 # v/s, 0 disables


    [[STEAMWORKS.CLIMBER.TALON]]
    name = "slave"
    type = "voltage"
    feedback_device = 0 # quad
    neutral_mode    = 1 # brake
    limit_mode      = 2 # disabled
    encoder_reversed = false
    output_reversed  = false
    current_limit    = 30 # amps, 0 disables

    voltage_ramp_rate = 0.0 # v/s, 0 disables

[STEAMWORKS.DEADEYE]
port = 5800

elevation_zero_angle = 6.0 # degrees
centerline_height = 83.91 # inches
camera_height = 19.25 # inches
camera_angle = 56.35 # degrees
degrees_per_tick = 0.00611


[STEAMWORKS.GEAR]
# settings for the gear intake motor voltage mode
load_voltage =  12.0
deploy_voltage = 8.0

# settings for the gear clamp servo position
# left servo
left_clamp_stage    = 0.75
right_clamp_stage   = 0.32

left_clamp_shut     = 0.5
right_clamp_shut    = 0.5

left_clamp_release  = 0.84
right_clamp_release = 0.2

left_clamp_stow     = 0.45 # not used
right_clamp_stow    = 0.6  # not used

# settings for the gear pivot motor position mode
pivot_zero =  825
pivot_up   = 1020 # ticks
pivot_down =    0 # ticks

    [[STEAMWORKS.GEAR.TALON]]
    name = "loader"
    type = "voltage"
    feedback_device = 0 # quad
    neutral_mode    = 1 # brake
    limit_mode      = 0 # use photo limit switch
    encoder_reversed = false
    output_reversed  = false
    current_limit    = 0 # amps, 0 disables

    voltage_ramp_rate = 0.0 # v/s, 0 disables

    [[STEAMWORKS.GEAR.TALON]]
    name = "pivot"
    type = "position"

    feedback_device = 0 # quad
    neutral_mode    = 1 # brake
    limit_mode      = 0 # use switches

    P      =    5.0
    I      =    0.0
    D      =  150.0
    F      =    0.0
    I_zone =      0

    voltage_ramp_rate              =   0.0 # v/s, 0 disables
    close_loop_ramp_rate           =   0.0 # v/s, 0 disables
    peak_output_voltage_forward    =   3.0 # v
    peak_output_voltage_reverse    =  -3.0 # v
    nominal_output_voltage_forward =   0.0 # v
    nominal_output_voltage_reverse =   0.0 # v
    allowable_closed_loop_error    =     0 # encoder ticks
    encoder_reversed = false
    output_reversed  = false
    current_limit    = 4 # amps, 0 disables


[STEAMWORKS.HOPPER]
voltage = 8.0

    [[STEAMWORKS.HOPPER.TALON]]
    name = "hopper"
    type = "voltage"
    feedback_device = 0 # quad
    neutral_mode    = 2 # coast
    limit_mode      = 2 # disabled
    encoder_reversed = false
    output_reversed  = false
    current_limit    = 0 # amps, 0 disables

    voltage_ramp_rate = 0.0 # v/s, 0 disables

[STEAMWORKS.INTAKE]
voltage = 12.0

    [[STEAMWORKS.INTAKE.TALON]]
    name = "intake"
    type = "voltage"
    feedback_device = 0 # quad
    neutral_mode    = 1 # brake
    limit_mode      = 2 # disabled
    encoder_reversed = false
    output_reversed  = false
    current_limit    = 20 # amps, 0 disables

    voltage_ramp_rate = 14.0 # v/s, 0 disables

[STEAMWORKS.SHOOTER]
# elevation motor absolute encoder position at zero
elevation_zero = 3698

    [[STEAMWORKS.SHOOTER.TALON]]
    # range 0-900 ticks/100ms
    # 650 practical max
    name = "shooter_wheel"
    type = "velocity"

    feedback_device = 0 # quad
    neutral_mode    = 2 # coast
    limit_mode      = 2 # soft and hard disabled

    P      =   20.0
    I      =    0.0
    D      =    0.0
    F      =    1.0
    I_zone =      0

    voltage_ramp_rate              =   0.0 # v/s, 0 disables
    close_loop_ramp_rate           =   0.0 # v/s, 0 disables
    peak_output_voltage_forward    =  12.0 # v
    peak_output_voltage_reverse    =  -0.5 # v
    nominal_output_voltage_forward =   0.0 # v
    nominal_output_voltage_reverse =   0.0 # v
    allowable_closed_loop_error    =     0 # encoder ticks
    encoder_reversed = false
    output_reversed  = false
    current_limit    = 50 # amps, 0 disables

    [[STEAMWORKS.SHOOTER.TALON]]
    # range 0 - 4500
    name = "shooter_elevation"
    type = "position"

    feedback_device = 0 # quad
    neutral_mode    = 1 # brake
    limit_mode      = 2 # soft and hard disabled

    P      =   10.0
    I      =    0.0
    D      =  150.0
    F      =    0.0
    I_zone =      0

    voltage_ramp_rate              =   0.0 # v/s, 0 disables
    close_loop_ramp_rate           =   0.0 # v/s, 0 disables
    peak_output_voltage_forward    =   7.0 # v
    peak_output_voltage_reverse    =  -6.0 # v
    nominal_output_voltage_forward =   0.0 # v
    nominal_output_voltage_reverse =   0.0 # v
    allowable_closed_loop_error    =     0 # encoder ticks
    encoder_reversed = false
    output_reversed  = false
    current_limit    = 5 # amps, 0 disables

[SIDEWINDER]
drive_dead_zone  = 0.08
drive_expo_scale = 0.75
azimuth_dead_zone  = 0.08
azimuth_expo_scale = 0.75
drive_sma_period = 5
azimuth_sma_period = 5

    [SIDEWINDER.SWERVE]
    wheelbase_width  = 26.4375 # inches
    wheelbase_length = 22.5    # inches

    shooter_rotation_point_X = 0.0
    shooter_rotation_point_Y = 0.0

        [[SIDEWINDER.SWERVE.TALON]]
        name = "azimuth"
        type = "motion_magic"

        feedback_device = 0 # quad
        neutral_mode    = 2 # coast
        limit_mode      = 2 # soft and hard disabled

        P      =   10.0
        I      =    0.0
        D      =   75.0
        F      =    0.8
        I_zone =      0

        # motion magic
        cruise_velocity =  800.0
        acceleration    = 6400.0

        voltage_ramp_rate              =   0.0 # v/s, 0 disables
        close_loop_ramp_rate           =   0.0 # v/s, 0 disables
        peak_output_voltage_forward    =  12.0 # v
        peak_output_voltage_reverse    = -12.0 # v
        nominal_output_voltage_forward =   0.0 # v
        nominal_output_voltage_reverse =   0.0 # v
        allowable_closed_loop_error    =     0 # encoder ticks
        encoder_reversed = false
        output_reversed  = false
        current_limit    = 20 # amps, 0 disables

        [[SIDEWINDER.SWERVE.TALON]]
        name = "drive"
        type = "voltage"
        setpoint_max = 12.0 # max volts

        feedback_device = 0 # quad
        neutral_mode    = 1 # brake
        limit_mode      = 2 # soft and hard disabled
        encoder_reversed = false
        output_reversed  = false
        current_limit    = 60 # amps, 0 disables

        voltage_ramp_rate = 0.0 # v/s, 0 disables

        [[SIDEWINDER.SWERVE.TALON]]
        # ticks 25 - 400 can step change within this range
        # 600 practical max, 1000 = 12v
        # 25 = .42 f/sec
        # 400 = 6.8 f/sec, linear between 25-400
        # 48.89 ticks per inch
        name = "drive_auton"
        type = "velocity"
        setpoint_max = 600.0 # ticks/100ms

        feedback_device = 0 # quad
        neutral_mode    = 2 # coast
        limit_mode      = 2 # soft and hard disabled

        P      =    2.0
        I      =    0.008
        D      =    0.0
        F      =    1.4
        I_zone =     25

        voltage_ramp_rate              =   0.0 # v/s, 0 disables
        close_loop_ramp_rate           =   0.0 # v/s, 0 disables
        peak_output_voltage_forward    =  12.0 # v
        peak_output_voltage_reverse    = -12.0 # v
        nominal_output_voltage_forward =   0.0 # v
        nominal_output_voltage_reverse =   0.0 # v
        allowable_closed_loop_error    =     0 # encoder ticks
        encoder_reversed = false
        output_reversed  = false
        current_limit    = 40 # amps, 0 disables

        [[SIDEWINDER.SWERVE.TALON]]
        # ticks 10 - 75, can experiment going down to 5 but only in down dir
        # at 10 will stop in 100ms
        # deadband will prevent hunting
        name = "drive_auton_slow_azimuth"
        type = "velocity"
        setpoint_max = 75.0 # ticks/100ms

        feedback_device = 0 # quad
        neutral_mode    = 2 # coast
        limit_mode      = 2 # soft and hard disabled

        P      =     2.0
        I      =     0.017 # if jerking, take down to 0.016, 0.015
        D      =    75.0 # then take down 5 at a time down to 50
        F      =     2.1
        I_zone =    20

        voltage_ramp_rate              =   0.0 # v/s, 0 disables
        close_loop_ramp_rate           =   0.0 # v/s, 0 disables
        peak_output_voltage_forward    =  12.0 # v
        peak_output_voltage_reverse    = -12.0 # v
        nominal_output_voltage_forward =   0.0 # v
        nominal_output_voltage_reverse =   0.0 # v
        allowable_closed_loop_error    =     0 # encoder ticks
        encoder_reversed = false
        output_reversed  = false
        current_limit    = 15 # amps, 0 disables

        [[SIDEWINDER.SWERVE.TALON]]
        # ticks 10 - 75, can experiment going down to 5 but only in down dir
        # at 10 will stop in 100ms
        # deadband will prevent hunting
        # ticks to inch 50.72
        name = "drive_auton_motion_magic"
        type = "motion_magic"
        # setpoint_max = 400.0 # ticks/100ms

        feedback_device = 0 # quad
        neutral_mode    = 2 # coast
        limit_mode      = 2 # soft and hard disabled

        P      =     1.5
        I      =     0.008
        D      =   150.0
        F      =     1.4
        I_zone =    25

        # motion magic
        cruise_velocity =  200.0
        acceleration    =  400.0


        voltage_ramp_rate              =   0.0 # v/s, 0 disables
        close_loop_ramp_rate           =   0.0 # v/s, 0 disables
        peak_output_voltage_forward    =  12.0 # v
        peak_output_voltage_reverse    = -12.0 # v
        nominal_output_voltage_forward =   0.0 # v
        nominal_output_voltage_reverse =   0.0 # v
        allowable_closed_loop_error    =     0 # encoder ticks
        encoder_reversed = false
        output_reversed  = false
        current_limit    = 40 # amps, 0 disables
