[DEADEYE.DEBUG]
framerate = 200
boiler = 0
gear = 100

[BOILER]
gui = true

[BOILER.CAMERA]
width  = 1280
height = 1024

exposure = -1.1 # dark outside
#exposure = -1.4 # bright light
#exposure = 0.5 # checking field of view

[BOILER.FRAME]
hsv_lower = [80, 100, 100]
hsv_upper = [100, 255, 255]
min_arc_length = 250.0

[GEAR.CAMERA]

[GEAR.FRAME]
hsv_lower = [70, 100, 100]
hsv_upper = [90, 255, 255]
min_arc_length = 50.0
azimuth_offset = 320

[LINK]
port = 5800
address = "10.27.67.2"
mode = "idle"
