[STEAMWORKS]
grapher = true

hopper_voltage = 8.0
intake_voltage = 12.0
climber_capture_voltage = 4.0
climber_climb_voltage =  12.0
climber_capture_current = 4.0

    [[STEAMWORKS.TALON]]
    name = "intake"
    type = "voltage"
    feedback_device = 0 # quad
    neutral_mode    = 1 # brake
    limit_mode      = 2 # disabled
    encoder_reversed = false
    output_reversed  = false
    current_limit    = 20 # amps, 0 disables

    voltage_ramp_rate = 14.0 # v/s, 0 disables

    [[STEAMWORKS.TALON]]
    name = "hopper"
    type = "voltage"
    feedback_device = 0 # quad
    neutral_mode    = 2 # coast
    limit_mode      = 2 # disabled
    encoder_reversed = false
    output_reversed  = false
    current_limit    = 0 # amps, 0 disables

    voltage_ramp_rate = 0.0 # v/s, 0 disables

    [[STEAMWORKS.TALON]]
    name = "climber_master"
    type = "voltage"
    feedback_device = 0 # quad
    neutral_mode    = 1 # coast
    limit_mode      = 2 # disabled
    encoder_reversed = false
    output_reversed  = true
    current_limit    = 40 # amps, 0 disables

    voltage_ramp_rate = 0.0 # v/s, 0 disables


    [[STEAMWORKS.TALON]]
    name = "climber_slave"
    type = "voltage"
    feedback_device = 0 # quad
    neutral_mode    = 1 # coast
    limit_mode      = 2 # disabled
    encoder_reversed = false
    output_reversed  = false
    current_limit    = 40 # amps, 0 disables

    voltage_ramp_rate = 0.0 # v/s, 0 disables

    [[STEAMWORKS.TALON]]
    name = "shooter_wheel"
    type = "velocity"

    feedback_device = 0 # quad
    neutral_mode    = 2 # coast
    limit_mode      = 2 # soft and hard disabled

    P      =   20.0
    I      =    0.0
    D      =    0.0
    F      =    1.0
    I_zone =      0

    voltage_ramp_rate              =   0.0 # v/s, 0 disables
    close_loop_ramp_rate           =   0.0 # v/s, 0 disables
    peak_output_voltage_forward    =  12.0 # v
    peak_output_voltage_reverse    =  -2.0 # v
    nominal_output_voltage_forward =   0.0 # v
    nominal_output_voltage_reverse =   0.0 # v
    allowable_closed_loop_error    =     0 # encoder ticks
    encoder_reversed = false
    output_reversed  = false
    current_limit    = 60 # amps, 0 disables

    [[STEAMWORKS.TALON]]
    name = "shooter_elevation"
    type = "position"

    feedback_device = 0 # quad
    neutral_mode    = 1 # brake
    limit_mode      = 0 # use switches

    P      =   10.0
    I      =    0.0
    D      =  150.0
    F      =    0.0
    I_zone =      0

    voltage_ramp_rate              =   0.0 # v/s, 0 disables
    close_loop_ramp_rate           =   0.0 # v/s, 0 disables
    peak_output_voltage_forward    =   4.0 # v
    peak_output_voltage_reverse    =  -5.0 # v
    nominal_output_voltage_forward =   0.0 # v
    nominal_output_voltage_reverse =   0.0 # v
    allowable_closed_loop_error    =     0 # encoder ticks
    encoder_reversed = false
    output_reversed  = false
    current_limit    = 0 # amps, 0 disables

    [[STEAMWORKS.TALON]]
    name = "shooter_elevation_zero"
    type = "voltage"
    feedback_device = 0 # quad
    neutral_mode    = 2 # coast
    limit_mode      = 0 # use switches, will disable in software during zero
    encoder_reversed = false
    output_reversed  = false
    current_limit    = 0 # amps, 0 disables

    voltage_ramp_rate = 0.0 # v/s, 0 disables


[SIDEWINDER]
drive_dead_zone  = 0.08
drive_expo_scale = 0.75
azimuth_dead_zone  = 0.08
azimuth_expo_scale = 0.75
drive_sma_period = 5
azimuth_sma_period = 5

# drive scale factor scales the 0.0 - 1.0 input to the appropriate value
# for the drive mode, e.g. 12.0 for voltage and max ticks/10ms for velocity
#drive_scale_factor = 900.0
drive_scale_factor = 12.0


    [SIDEWINDER.SWERVE]
    lf_zero = 998
    rf_zero = 952
    lr_zero = 3681
    rr_zero = 961

    wheelbase_width  = 26.4375 # inches
    wheelbase_length = 22.5    # inches

    shooter_rotation_point_X = 0.0
    shooter_rotation_point_Y = 0.0

        [[SIDEWINDER.SWERVE.TALON]]
        name = "azimuth"
        type = "position"

        feedback_device = 0 # quad
        neutral_mode    = 2 # coast
        limit_mode      = 2 # soft and hard disabled

        P      =   10.0
        I      =    0.0
        D      =  150.0
        F      =    0.0
        I_zone =      0

        voltage_ramp_rate              =  0.0 # v/s, 0 disables
        close_loop_ramp_rate           =  0.0 # v/s, 0 disables
        peak_output_voltage_forward    =  5.0 # v
        peak_output_voltage_reverse    = -5.0 # v
        nominal_output_voltage_forward =  0.0 # v
        nominal_output_voltage_reverse =  0.0 # v
        allowable_closed_loop_error    =    0 # encoder ticks
        encoder_reversed = false
        output_reversed  = false
        current_limit    = 0 # amps, 0 disables

        [[SIDEWINDER.SWERVE.TALON]]
        name = "drive"
        type = "voltage"

        feedback_device = 0 # quad
        neutral_mode    = 1 # brake
        limit_mode      = 2 # soft and hard disabled
        encoder_reversed = false
        output_reversed  = false
        current_limit    = 60 # amps, 0 disables

        voltage_ramp_rate = 0.0 # v/s, 0 disables

        [[SIDEWINDER.SWERVE.TALON]]
        # ticks 25 - 400 can step change within this range
        # 600 practical max, 1000 = 12v
        # 25 = .42 f/sec
        # 400 = 6.8 f/sec, linear between 25-400
        # 48.89 ticks per inch
        name = "drive_auton"
        type = "velocity"

        feedback_device = 0 # quad
        neutral_mode    = 2 # coast
        limit_mode      = 2 # soft and hard disabled

        P      =    2.0
        I      =    0.008
        D      =    0.0
        F      =    1.4
        I_zone =     25

        voltage_ramp_rate              =   0.0 # v/s, 0 disables
        close_loop_ramp_rate           =   0.0 # v/s, 0 disables
        peak_output_voltage_forward    =  12.0 # v
        peak_output_voltage_reverse    = -12.0 # v
        nominal_output_voltage_forward =   0.0 # v
        nominal_output_voltage_reverse =   0.0 # v
        allowable_closed_loop_error    =     0 # encoder ticks
        encoder_reversed = false
        output_reversed  = false
        current_limit    = 40 # amps, 0 disables
