[STEAMWORKS]
grapher = false

hopper_voltage = 8.0
intake_voltage = 12.0

    [[STEAMWORKS.TALON]]
    name = "intake"
    type = "voltage"
    feedback_device = 0 # quad
    neutral_mode    = 1 # brake
    limit_mode      = 2 # disabled
    encoder_reversed = false
    output_reversed  = false
    current_limit    = 20 # amps, 0 disables

    voltage_ramp_rate = 14.0 # v/s, 0 disables

    [[STEAMWORKS.TALON]]
    name = "hopper"
    type = "voltage"
    feedback_device = 0 # quad
    neutral_mode    = 2 # coast
    limit_mode      = 2 # disabled
    encoder_reversed = false
    output_reversed  = false
    current_limit    = 0 # amps, 0 disables

    voltage_ramp_rate = 0.0 # v/s, 0 disables

[SIDEWINDER]
drive_dead_zone  = 0.08
drive_expo_scale = 0.75
azimuth_dead_zone  = 0.08
azimuth_expo_scale = 0.75
drive_sma_period = 5
azimuth_sma_period = 5

# drive scale factor scales the 0.0 - 1.0 input to the appropriate value
# for the drive mode, e.g. 12.0 for voltage and max ticks/10ms for velocity
drive_scale_factor = 12.0

    [SIDEWINDER.SWERVE]
    lf_zero = 1002
    rf_zero = 959
    lr_zero = 981
    rr_zero = 969

    wheelbase_width  = 26.4375 # inches
    wheelbase_length = 22.5    # inches

    shooter_rotation_point_X = 0.0
    shooter_rotation_point_Y = 0.0

        [[SIDEWINDER.SWERVE.TALON]]
        name = "azimuth"
        type = "position"

        # feedback device
        # quad         = 0
        # analog pot   = 2
        # analog enc   = 3
        # enc rising   = 4
        # enc falling  = 5
        # mag relative = 6
        # mag absolute = 7
        # pulse width  = 8
        feedback_device = 0 # quad

        # neutral mode
        # jumper = 0
        # brake = 1
        # coast = 2
        neutral_mode    = 2 # coast

        # limit mode
        # only use switches for limits             = 0
        # use both switches and soft limits        = 1
        # disable switches and disable soft limits = 2
        limit_mode      = 2 # soft and hard disabled

        P      =   10.0
        I      =    0.0
        D      =  150.0
        F      =    0.0
        I_zone =      0

        voltage_ramp_rate              =  0.0 # v/s, 0 disables
        close_loop_ramp_rate           =  0.0 # v/s, 0 disables
        peak_output_voltage_forward    =  5.0 # v
        peak_output_voltage_reverse    = -5.0 # v
        nominal_output_voltage_forward =  0.0 # v
        nominal_output_voltage_reverse =  0.0 # v
        allowable_closed_loop_error    =    0 # encoder ticks
        encoder_reversed = false
        output_reversed  = false
        current_limit    = 0 # amps, 0 disables

        [[SIDEWINDER.SWERVE.TALON]]
        name = "drive_voltage"
        type = "voltage"

        feedback_device = 0 # quad
        neutral_mode    = 1 # brake
        limit_mode      = 2 # soft and hard disabled
        encoder_reversed = false
        output_reversed  = false
        current_limit    = 60 # amps, 0 disables

        voltage_ramp_rate = 0.0 # v/s, 0 disables
