# feedback device
# quad         = 0
# analog pot   = 2
# analog enc   = 3
# enc rising   = 4
# enc falling  = 5
# mag relative = 6
# mag absolute = 7
# pulse width  = 8

# neutral mode
# jumper = 0
# brake = 1
# coast = 2

# limit mode
# only use switches for limits             = 0
# use both switches and soft limits        = 1
# disable switches and disable soft limits = 2
[SIDEWINDER]
joystick_dead_zone  = 0.08
joystick_expo_coeff = 0.5

[SIDEWINDER.AZIMUTH]
lf_zero = 1030
rf_zero = 1027
lr_zero = 1032
rr_zero = 1002

feedback_device = 6 # mag relative
neutral_mode    = 2 # coast
limit_mode      = 2 # soft and hard disabled

P      =   12.0
I      =    0.0
D      =  200.0
F      =    0.0
I_zone =      0

voltage_ramp_rate              =  0.0 # v/s, 0 disables
close_loop_ramp_rate           =  0.0 # v/s, 0 disables
peak_output_voltage_forward    =  9.0 # v
peak_output_voltage_reverse    = -9.0 # v
nominal_output_voltage_forward =  0.0 # v
nominal_output_voltage_reverse =  0.0 # v
allowable_closed_loop_error    =    0 # encoder ticks
encoder_reversed = false
output_reversed  = false
