[DEADEYE]

gui = true

[DEADEYE.DEBUG]
# display debug info if the settings below are set > 0
# number is frame interval
framerate = 100
boiler = 100
gear = 100

[BOILER.CAMERA]
width  = 1280
height = 1024
exposure = -1.0

[BOILER.FRAME]
hsv_lower = [80, 100, 100]
hsv_upper = [100, 255, 255]
min_arc_length = 250.0

[GEAR.CAMERA]
azimuth_offset = 177

[GEAR.FRAME]
hsv_lower = [60, 100, 100]
hsv_upper = [80, 255, 255]
min_arc_length = 50.0

[LINK]
port = 5800
address = "10.27.67.2"
