[DEADEYE]

[CAMERA]
width  = 1280
height = 1024
exposure = -1.0

[FRAME]
hsv_lower = [80, 100, 100]
hsv_upper = [100, 255, 255]
min_arc_length = 250.0

[LINK]
port = "/dev/ttyTHS2"
speed = 115200
timeout = 1000 # ms
