# deadeye configuration
[logging]
level = "debug"

[camera]
exposure = 10

[robot]
address = "192.168.1.69"
port    = "5804"

[target]
hsv_lower = [65, 105, 0]
hsv_upper = [125, 105, 0]
perimeter = 250
