# deadeye configuration
[logging]
level = "debug"

[robot]
address = "192.168.1.69"
port    = "5804"

[color.lower]
hue        = 65.0
saturation = 105.0
value      = 0.0

[color.upper]
hue        = 125.0
saturation = 180.0
value      = 90.0
